// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"apps/services-dependencies/services-proxy-handler/internal/infra/web/handlers"
)

// Injectors from wire.go:

func NewHealthzHandler() *handlers.WebHealthzHandler {
	webHealthzHandler := handlers.NewWebHealthzHandler()
	return webHealthzHandler
}

func NewTorProxyHandler() *handlers.TorProxyHandler {
	torProxyHandler := handlers.NewTorProxyHandler()
	return torProxyHandler
}
