// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"apps/services-orchestration/services-file-catalog-handler/internal/entity"
	"apps/services-orchestration/services-file-catalog-handler/internal/infra/database"
	"apps/services-orchestration/services-file-catalog-handler/internal/infra/web/handlers"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func NewWebFileCatalogHandler(client *mongo.Client, database2 string) *handlers.WebFileCatalogHandler {
	fileCatalogRepository := database.NewFileCatalogRepository(client, database2)
	webFileCatalogHandler := handlers.NewWebFileCatalogHandler(fileCatalogRepository)
	return webFileCatalogHandler
}

func NewHealthzHandler() *handlers.WebHealthzHandler {
	webHealthzHandler := handlers.NewWebHealthzHandler()
	return webHealthzHandler
}

// wire.go:

var setFileCatalogRepositoryDependency = wire.NewSet(database.NewFileCatalogRepository, wire.Bind(
	new(entity.FileCatalogInterface),
	new(*database.FileCatalogRepository),
),
)
