
POST http://localhost:8002/configs HTTP/1.1
Content-Type: application/json

{
  "name": "ceaf-config",
  "active": true,
  "frequency": "daily",
  "service": "spark-batch-bronze",
  "source": "ceaf",
  "context": "br",
  "input_method": "GenerateInputUsingBucketUriAndPartition",
  "output_method": "event",
  "depends_on": [{
    "service": "file-unzip",
    "source": "ceaf"
  }],
  "service_parameters": {
    "job_handler": "default"
  },
  "job_parameters": {}
}





###
POST http://localhost:8002/configs/update HTTP/1.1
Content-Type: application/json

{
  "name": "ceaf-config",
  "active": true,
  "frequency": "daily",
  "service": "spark-batch-bronze",
  "source": "ceaf",
  "context": "br",
  "input_method": "",
  "output_method": "event",
  "depends_on": [{
    "service": "file-unzip",
    "source": "ceaf"
  }],
  "service_parameters": {
    "job_handler": "default"
  },
  "job_parameters": {}
}




###

GET http://localhost:8002/configs HTTP/1.1

###

GET http://localhost:8002/configs/file-downloader-ceaf HTTP/1.1

###

GET http://localhost:8002/configs/service/source-watcher HTTP/1.1

###

GET http://localhost:8002/configs/service/file-downloader/source/john-watson-rooney/context/br HTTP/1.1

###

GET http://localhost:8002/configs/service/source-watcher/source/annual-reports HTTP/1.1

###

