###

POST http://localhost:8001/inputs/context/br/service/source-watcher/source/annual-reports HTTP/1.1
Content-Type: application/json

{
  "data": {
    "reference": {
      "year": 2023,
      "month": 11,
      "day": 12
    }
  }
}

###
POST http://localhost:8001/inputs/context/br/service/file-downloader/source/annual-reports HTTP/1.1
Content-Type: application/json

{
  "data": {
    "documentUri": "http://minio:9000/process-input-br-source-annual-reports/ambac-financial-group-inc-1/20231112/NASDAQ_AMBC_2022.html",
    "partition": "ambac-financial-group-inc-1",
    "targetDocument": "NASDAQ_AMBC_2022.pdf"
  }
}

###

POST http://localhost:8001/inputs/context/br/service/source-watcher/source/ceaf HTTP/1.1
Content-Type: application/json

{
  "data": {
    "reference": {
      "year": 2023,
      "month": 11,
      "day": 12
    }
  }
}

###

POST http://localhost:8001/inputs/context/br/service/file-downloader/source/john-watson-rooney HTTP/1.1
Content-Type: application/json

{
  "data": {
    "videoId": "4WQba4KwmRs"
  }
}

###

GET http://localhost:8001/inputs/service/source-watcher HTTP/1.1

###

GET http://localhost:8001/inputs/service/file-downloader HTTP/1.1

###

GET http://localhost:8001/inputs/service/spark-batch-bronze HTTP/1.1

###

GET http://localhost:8001/inputs/service/file-unzip HTTP/1.1

###

GET http://localhost:8001/inputs/service/speech-transcriber HTTP/1.1

###
