// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"apps/services-orchestration/services-jobs-handler/internal/entity"
	"apps/services-orchestration/services-jobs-handler/internal/infra/database"
	"apps/services-orchestration/services-jobs-handler/internal/infra/web/handlers"
	"github.com/google/wire"
	"go.mongodb.org/mongo-driver/mongo"
)

// Injectors from wire.go:

func NewWebJobParamsHttpGatewayHandler(client *mongo.Client, database2 string) *handlers.WebJobParamsHttpGatewayHandler {
	httpGatewayParamsRepository := database.NewHttpGatewayParamsRepository(client, database2)
	httpGatewayParamsVersionRepository := database.NewHttpGatewayParamsVersionRepository(client, database2)
	webJobParamsHttpGatewayHandler := handlers.NewWebJobParamsHttpGatewayHandler(httpGatewayParamsRepository, httpGatewayParamsVersionRepository)
	return webJobParamsHttpGatewayHandler
}

func NewHealthzHandler() *handlers.WebHealthzHandler {
	webHealthzHandler := handlers.NewWebHealthzHandler()
	return webHealthzHandler
}

// wire.go:

var setHttpGatewayParamsRepositoryDependency = wire.NewSet(database.NewHttpGatewayParamsRepository, wire.Bind(
	new(entity.HttpGatewayParamsInterface),
	new(*database.HttpGatewayParamsRepository),
),
)

var setHttpGatewayParamsVersionRepositoryDependency = wire.NewSet(database.NewHttpGatewayParamsVersionRepository, wire.Bind(
	new(entity.HttpGatewayParamsVersionInterface),
	new(*database.HttpGatewayParamsVersionRepository),
),
)
